//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlutoniumEasyInstaller.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PlutoniumEasyInstaller.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AlreadyRunningWarning {
            get {
                return ResourceManager.GetString("AlreadyRunningWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An anti-malware program is detected.
        ///It is recommended to disable them if you want a smooth setup (especially anything named something like Active Threat Defense).
        ///You can enable them after the setup is complete.
        ///
        ///
        ///If you continue without disabling your anti-malware, you will likely trigger your anti-malware program 1-3 times. You will need to add whatever it catches as an exception and restart the installer..
        /// </summary>
        public static string AntiMalwareWarning {
            get {
                return ResourceManager.GetString("AntiMalwareWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anti-malware detected.
        /// </summary>
        public static string AntiMalwareWarningHeader {
            get {
                return ResourceManager.GetString("AntiMalwareWarningHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        public static string BrowseFolder {
            get {
                return ResourceManager.GetString("BrowseFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Complete_Exit {
            get {
                return ResourceManager.GetString("Complete_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to Start!.
        /// </summary>
        public static string Complete_Header {
            get {
                return ResourceManager.GetString("Complete_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plutonium for Call of Duty: Black Ops 2 has finished installing..
        /// </summary>
        public static string Complete_Info {
            get {
                return ResourceManager.GetString("Complete_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play!.
        /// </summary>
        public static string Complete_Play {
            get {
                return ResourceManager.GetString("Complete_Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating shortcuts....
        /// </summary>
        public static string CreatingShortcuts {
            get {
                return ResourceManager.GetString("CreatingShortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download was cancelled!.
        /// </summary>
        public static string DownloadCancelled {
            get {
                return ResourceManager.GetString("DownloadCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download complete!.
        /// </summary>
        public static string DownloadComplete {
            get {
                return ResourceManager.GetString("DownloadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download failed! Reason: {0}.
        /// </summary>
        public static string DownloadFailed {
            get {
                return ResourceManager.GetString("DownloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game not found!.
        /// </summary>
        public static string GameNotFound {
            get {
                return ResourceManager.GetString("GameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error during installation. Please open this app and try again..
        /// </summary>
        public static string InstallationError {
            get {
                return ResourceManager.GetString("InstallationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to install.
        /// </summary>
        public static string InstallationErrorHeader {
            get {
                return ResourceManager.GetString("InstallationErrorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next &gt;.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough space.
        /// </summary>
        public static string NotEnoughSpaceHeader {
            get {
                return ResourceManager.GetString("NotEnoughSpaceHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call of Duty: Black Ops 2 installed..
        /// </summary>
        public static string PiryInstall_BO2Downloaded {
            get {
                return ResourceManager.GetString("PiryInstall_BO2Downloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading Call of Duty: Black Ops 2....
        /// </summary>
        public static string PiryInstall_DownloadingBO2 {
            get {
                return ResourceManager.GetString("PiryInstall_DownloadingBO2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading Call of Duty: Black Ops 2.
        /// </summary>
        public static string PiryInstall_Header {
            get {
                return ResourceManager.GetString("PiryInstall_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About 14 GB - this may take a while depending on your internet connection....
        /// </summary>
        public static string PiryInstall_Notice {
            get {
                return ResourceManager.GetString("PiryInstall_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The drive selected doesn&apos;t have enough free space. At least 22 GB is required..
        /// </summary>
        public static string PirySetup_BO2NotEnoughSpace {
            get {
                return ResourceManager.GetString("PirySetup_BO2NotEnoughSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose where you want Call of Duty: Black Ops 2 to be installed..
        /// </summary>
        public static string PirySetup_FolderHelp {
            get {
                return ResourceManager.GetString("PirySetup_FolderHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A minimum of 21 GB is required..
        /// </summary>
        public static string PirySetup_FolderSize {
            get {
                return ResourceManager.GetString("PirySetup_FolderSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a folder.
        /// </summary>
        public static string PirySetup_Header {
            get {
                return ResourceManager.GetString("PirySetup_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select where you want to install Call of Duty: Black Ops 2.
        /// </summary>
        public static string PirySetup_SelectNewBO2Folder {
            get {
                return ResourceManager.GetString("PirySetup_SelectNewBO2Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config file created..
        /// </summary>
        public static string PlutoInstall_ConfigFileCreated {
            get {
                return ResourceManager.GetString("PlutoInstall_ConfigFileCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating config file....
        /// </summary>
        public static string PlutoInstall_CreatingConfigFile {
            get {
                return ResourceManager.GetString("PlutoInstall_CreatingConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading ReShade....
        /// </summary>
        public static string PlutoInstall_DownloadingReShade {
            get {
                return ResourceManager.GetString("PlutoInstall_DownloadingReShade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Almost there!.
        /// </summary>
        public static string PlutoInstall_Header {
            get {
                return ResourceManager.GetString("PlutoInstall_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing Plutonium....
        /// </summary>
        public static string PlutoInstall_InstallingPlutonium {
            get {
                return ResourceManager.GetString("PlutoInstall_InstallingPlutonium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plutonium installed..
        /// </summary>
        public static string PlutoInstall_PlutoniumInstalled {
            get {
                return ResourceManager.GetString("PlutoInstall_PlutoniumInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReShade download was cancelled!.
        /// </summary>
        public static string PlutoInstall_ReShadeDownloadCancelled {
            get {
                return ResourceManager.GetString("PlutoInstall_ReShadeDownloadCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReShade download complete!.
        /// </summary>
        public static string PlutoInstall_ReShadeDownloadComplete {
            get {
                return ResourceManager.GetString("PlutoInstall_ReShadeDownloadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReShade download failed!.
        /// </summary>
        public static string PlutoInstall_ReShadeDownloadFailed {
            get {
                return ResourceManager.GetString("PlutoInstall_ReShadeDownloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReShade installation failed!.
        /// </summary>
        public static string PlutoInstall_ReShadeInstallationFailed {
            get {
                return ResourceManager.GetString("PlutoInstall_ReShadeInstallationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desktop Shortcut.
        /// </summary>
        public static string PlutoSetup_DesktopShortcut {
            get {
                return ResourceManager.GetString("PlutoSetup_DesktopShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Plutonium.
        /// </summary>
        public static string PlutoSetup_Header {
            get {
                return ResourceManager.GetString("PlutoSetup_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install ReShade (sick ass post-processing effects).
        /// </summary>
        public static string PlutoSetup_ReShade {
            get {
                return ResourceManager.GetString("PlutoSetup_ReShade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Menu Shortcut.
        /// </summary>
        public static string PlutoSetup_StartShortcut {
            get {
                return ResourceManager.GetString("PlutoSetup_StartShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcuts created..
        /// </summary>
        public static string ShortcutsCreated {
            get {
                return ResourceManager.GetString("ShortcutsCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call of Duty: Black Ops 2 could not be found on your computer.
        ///Could you show me where it is?.
        /// </summary>
        public static string Start_BO2NotFound {
            get {
                return ResourceManager.GetString("Start_BO2NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This installer will help you install Plutonium for Call of Duty: Black Ops 2 (T6).
        /// </summary>
        public static string Start_InstallerInfo {
            get {
                return ResourceManager.GetString("Start_InstallerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder selected does not contain Call of Duty: Black Ops 2.
        ///Try again?.
        /// </summary>
        public static string Start_InvalidBO2Folder {
            get {
                return ResourceManager.GetString("Start_InvalidBO2Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For users who do not have Call of Duty: Black Ops 2 installed on their computer..
        /// </summary>
        public static string Start_NonSteamInfo {
            get {
                return ResourceManager.GetString("Start_NonSteamInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-Steam Owners.
        /// </summary>
        public static string Start_NonSteamOwners {
            get {
                return ResourceManager.GetString("Start_NonSteamOwners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for downloading Plutonium!.
        /// </summary>
        public static string Start_PlutoniumWelcome {
            get {
                return ResourceManager.GetString("Start_PlutoniumWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the COD: Black Ops 2 folder..
        /// </summary>
        public static string Start_SelectBO2Folder {
            get {
                return ResourceManager.GetString("Start_SelectBO2Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For users who already own and have Call of Duty: Black Ops 2 installed on their computer..
        /// </summary>
        public static string Start_SteamInfo {
            get {
                return ResourceManager.GetString("Start_SteamInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam Owners.
        /// </summary>
        public static string Start_SteamOwners {
            get {
                return ResourceManager.GetString("Start_SteamOwners", resourceCulture);
            }
        }
    }
}
